# Generated by Django 4.2.7 on 2024-02-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='bname',
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
