# Generated by Django 4.2.7 on 2024-02-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_bank_name_bank_bname_alter_branch_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bname',
            new_name='bank_name',
        ),
    ]
