# Generated by Django 4.2.7 on 2024-02-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_bname_bank_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='bname',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='bank_name',
            new_name='bname',
        ),
    ]
